
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/aandryashin/matchers"

[[constraint]]
  name = "github.com/aerokube/selenoid"
  version = "1.3.9"

[[override]]
  name = "github.com/docker/cli"
  revision = "608b6632b05840a5cd9c6ad837d1fa1118444d41"

[[constraint]]
  revision = "ebfec748347a9af6793c723f8859afcd906860fb"
  name = "github.com/google/go-github"

[[constraint]]
  revision = "fd2fe803496897db70c236ee244f41487ea92ec2"
  name = "github.com/heroku/docker-registry-client"

[[constraint]]
  revision = "4fdf99ab29366514c69ccccddab5dc58b8d84062"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.18"

[[constraint]]
  revision = "256737ac55c46798123f754ab7d2c784e2c71783"
  name = "vbom.ml/util"

[[constraint]]
  name = "github.com/fatih/color"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "v0.0.9"

[[constraint]]
  name = "github.com/aerokube/util"
  branch = "master"
